# Generated by Django 4.0.3 on 2022-03-25 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 12, 26, 2, 261260, tzinfo=utc)),
        ),
    ]
