# Generated by Django 4.0.3 on 2022-03-25 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0004_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='owner',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='g', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 13, 4, 40, 483992, tzinfo=utc)),
        ),
    ]
