# Generated by Django 4.0.3 on 2022-03-25 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_remove_userinfo_owner_userinfo_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 13, 7, 55, 136677, tzinfo=utc)),
        ),
    ]
