# Generated by Django 4.0.3 on 2022-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0008_alter_userinfo_birthday_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(),
        ),
    ]
