# Generated by Django 4.0.3 on 2022-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0009_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
