# Generated by Django 4.0.3 on 2022-03-29 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0012_chat_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(max_length=100)),
                ('receive', models.CharField(max_length=100)),
                ('isshow', models.BooleanField(default=True)),
                ('isread', models.BooleanField(default=False)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bridge.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(max_length=100)),
                ('receive', models.CharField(max_length=100)),
                ('isshow', models.BooleanField(default=True)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bridge.chatmessage')),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
