# Generated by Django 4.0.3 on 2022-03-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0013_chatmessage_chatreceive_chatsend_delete_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatreceive',
            old_name='receive',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatreceive',
            old_name='send',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='chatsend',
            old_name='receive',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatsend',
            old_name='send',
            new_name='sender',
        ),
    ]
