# Generated by Django 4.0.3 on 2022-03-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0014_rename_receive_chatreceive_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsend',
            name='chat_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='isread_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='isshow_receiver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='isshow_sender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.CharField(default='e', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default='z', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatReceive',
        ),
        migrations.DeleteModel(
            name='ChatSend',
        ),
    ]
