# Generated by Django 4.0.3 on 2022-03-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0015_remove_chatsend_chat_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.CharField(max_length=100)),
                ('discuss', models.IntegerField()),
                ('isshow', models.BooleanField(default=1)),
                ('reply', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('starter', models.CharField(max_length=100)),
                ('isshow', models.BooleanField(default=1)),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_id', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('discuss', models.IntegerField()),
                ('comment', models.IntegerField(null=True)),
            ],
        ),
    ]
