# Generated by Django 4.0.3 on 2022-03-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0016_comment_discuss_discusstag_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
