# Generated by Django 4.0.3 on 2022-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0017_alter_discuss_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='discuss',
            field=models.CharField(max_length=100),
        ),
    ]
