# Generated by Django 4.0.3 on 2022-04-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0018_alter_dynamic_discuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discusstag',
            name='discuss_id',
        ),
        migrations.AddField(
            model_name='discusstag',
            name='discuss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.discuss'),
        ),
    ]
