# Generated by Django 4.0.3 on 2022-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0020_alter_discusstag_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discusstag',
            name='discuss',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
