# Generated by Django 4.0.3 on 2022-04-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0021_alter_discusstag_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discusstag',
            name='discuss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='bridge.discuss'),
        ),
    ]
