# Generated by Django 4.0.3 on 2022-04-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0023_alter_comment_discuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='isshow',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='notshow',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='replyto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.comment'),
        ),
    ]
