# Generated by Django 4.0.3 on 2022-04-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0024_remove_comment_isshow_remove_comment_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.comment'),
        ),
    ]
