# Generated by Django 4.0.3 on 2022-04-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0025_alter_comment_replyto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='text',
        ),
        migrations.AddField(
            model_name='notify',
            name='event_type',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notify',
            name='from_who',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
