# Generated by Django 4.0.3 on 2022-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0027_notify_discuss_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussWithTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('starter', models.CharField(max_length=100)),
                ('isshow', models.BooleanField(default=1)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'discuss_with_tag',
            },
        ),
    ]
