# Generated by Django 4.0.3 on 2022-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0030_report_reason_alter_report_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
